id: P008182
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG12427
  title: བཀའ་བློན་བཤད་སྒྲས་བརྩམས་པའི་ཡིག་བསྐུར་རྣམ་གཞག
  author: ''
  volumes:
    35afdb53b2394af8bd7540ac337b4ef8:
      image_group_id: I1KG12455
      title: ''
      volume_number: 1
      total_pages: 106
      base_file: v001.txt
