id: ID7D1CB77
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:14:21+00:00'
last_modified: '2022-06-09T05:04:16.325467+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12427
  title: བཀའ་བློན་བཤད་སྒྲས་བརྩམས་པའི་ཡིག་བསྐུར་རྣམ་གཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    57B3:
      image_group_id: I1KG12455
      title: ''
      total_pages: 106
      order: 1
      base_file: 57B3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
